"""
ChromaDB Vector Database Setup — Sentinel Historian Pillar

Initializes and manages a local ChromaDB instance for the Sentinel Sentiment Engine.
Provides typed client wrapper, collection definitions for market events and SEC filings,
and helper functions for database initialization and teardown.

Used by sentinel/historian/rag_query.py to store and retrieve embeddings of:
  - Historical market events (price movements, catalysts, anomalies)
  - SEC filings (8-K, 10-Q, 10-K summaries)
  - News headlines and sentiment snapshots

This module is idempotent: calling init_db() multiple times safely re-uses existing DB.
"""

import os
import sqlite3
from pathlib import Path
from typing import Optional, List, Dict, Any
import chromadb
from chromadb.config import Settings


# Module-level globals
_DB_DIR = Path(os.getenv("SENTINEL_DB_DIR", "./sentinel_data"))
_CHROMA_DB_PATH = _DB_DIR / "chromadb"
_SQLITE_BACKUP_PATH = _DB_DIR / "sentinel_corpus.db"


class SentinelChromaClient:
    """Typed wrapper around ChromaDB client for Sentinel collections."""

    def __init__(self, client: chromadb.Client):
        """Initialize wrapper with ChromaDB client instance."""
        self._client = client
        self._collections: Dict[str, chromadb.Collection] = {}

    def get_or_create_collection(
        self, collection_name: str, metadata: Optional[Dict[str, Any]] = None
    ) -> chromadb.Collection:
        """Get existing collection or create new one with optional metadata."""
        if collection_name not in self._collections:
            self._collections[collection_name] = self._client.get_or_create_collection(
                name=collection_name,
                metadata=metadata or {},
            )
        return self._collections[collection_name]

    def add_documents(
        self,
        collection_name: str,
        ids: List[str],
        documents: List[str],
        metadatas: Optional[List[Dict[str, Any]]] = None,
    ) -> None:
        """Add documents to a collection with embeddings auto-generated by ChromaDB."""
        collection = self.get_or_create_collection(collection_name)
        collection.add(ids=ids, documents=documents, metadatas=metadatas or [])

    def query_collection(
        self,
        collection_name: str,
        query_texts: List[str],
        n_results: int = 5,
    ) -> Dict[str, Any]:
        """Query collection and return top-k similar documents."""
        collection = self.get_or_create_collection(collection_name)
        results = collection.query(query_texts=query_texts, n_results=n_results)
        return results

    def delete_collection(self, collection_name: str) -> None:
        """Delete a collection from the database."""
        if collection_name in self._collections:
            del self._collections[collection_name]
        self._client.delete_collection(name=collection_name)

    def list_collections(self) -> List[str]:
        """List all collection names in the database."""
        return [c.name for c in self._client.list_collections()]


def init_db() -> SentinelChromaClient:
    """Initialize ChromaDB with Sentinel collections and return typed client."""
    _DB_DIR.mkdir(parents=True, exist_ok=True)
    _CHROMA_DB_PATH.mkdir(parents=True, exist_ok=True)

    # Configure ChromaDB to persist to disk
    settings = Settings(
        chroma_db_impl="duckdb+parquet",
        persist_directory=str(_CHROMA_DB_PATH),
        anonymized_telemetry=False,
    )
    client = chromadb.Client(settings)

    # Wrap in typed client
    sentinel_client = SentinelChromaClient(client)

    # Initialize standard collections
    sentinel_client.get_or_create_collection(
        "market_events",
        metadata={
            "description": "Historical market events (price moves, catalysts, anomalies)",
            "domain": "historical_events",
        },
    )
    sentinel_client.get_or_create_collection(
        "sec_filings",
        metadata={
            "description": "SEC filing summaries (8-K, 10-Q, 10-K)",
            "domain": "regulatory",
        },
    )
    sentinel_client.get_or_create_collection(
        "news_sentiment",
        metadata={
            "description": "News headlines and sentiment snapshots",
            "domain": "news_sentiment",
        },
    )
    sentinel_client.get_or_create_collection(
        "reddit_sentiment",
        metadata={
            "description": "Reddit discussion threads and community signals",
            "domain": "social_sentiment",
        },
    )

    return sentinel_client


def seed_market_events(client: SentinelChromaClient) -> None:
    """Seed market_events collection with canonical historical events for RAG context."""
    events = [
        {
            "id": "event_2023_svb_collapse",
            "document": "SVB (Silicon Valley Bank) collapsed on March 10, 2023 due to unrealized losses on bond portfolio amid rising interest rates. Triggered sector-wide bank stock selloff and depositor flight. VIX spiked to 28.",
            "metadata": {"date": "2023-03-10", "ticker": "SVBI", "category": "bank_crisis"},
        },
        {
            "id": "event_2023_ftx_fraud",
            "document": "FTX crypto exchange imploded in Nov 2022 due to fraud by founder Sam Bankman-Fried. Wiped out $8B in customer funds. Triggered crypto sector decline and contagion to hedge funds like Genesis.",
            "metadata": {"date": "2022-11-08", "ticker": "FTT", "category": "fraud"},
        },
        {
            "id": "event_2022_elon_twitter",
            "document": "Elon Musk acquired Twitter for $44B in Oct 2022. Implemented mass layoffs (50% workforce), API changes, and advertiser exodus. Stock market initially rallied on activist investor narrative.",
            "metadata": {"date": "2022-10-27", "ticker": "TWTR", "category": "acquisition"},
        },
        {
            "id": "event_2022_inflation_pivot",
            "document": "Fed raised rates 75bp in June and July 2022 in aggressive inflation-fighting stance. Signaled sustained 'higher for longer' terminal rate (4.5%). Triggered broad market decline, yield curve inversion.",
            "metadata": {"date": "2022-06-15", "ticker": "SPY", "category": "macro_policy"},
        },
        {
            "id": "event_2024_meta_recovery",
            "document": "Meta (Facebook) recovered from 2023 lows as AI spending accelerated and reels/ads revenue grew. Stock rose 140%+ YTD 2024. Market rotated into Magnificent 7 mega-cap tech stocks.",
            "metadata": {"date": "2024-01-01", "ticker": "META", "category": "sector_rotation"},
        },
    ]

    ids = [e["id"] for e in events]
    documents = [e["document"] for e in events]
    metadatas = [e["metadata"] for e in events]

    client.add_documents("market_events", ids, documents, metadatas)


def seed_sec_filings(client: SentinelChromaClient) -> None:
    """Seed sec_filings collection with canonical filing excerpts for RAG context."""
    filings = [
        {
            "id": "filing_tesla_8k_2023_price_cut",
            "document": "Tesla 8-K (Jan 2023): Announced significant price reductions across product line to drive volume growth amid demand softening. CFO noted gross margins under pressure but long-term EV adoption thesis intact.",
            "metadata": {"ticker": "TSLA", "form": "8
