"""
Daily summary printer for Sentinel Sentiment Engine.

Reads the latest post-mortem JSON (generated by postmortem.py) and prints
a concise console summary of Sentinel's performance: accuracy, confidence
calibration, top predictions, and anomalies flagged by the Judge.

Integrates into the daily build pipeline to surface actionable insights
without requiring manual log inspection.
"""

import json
import os
from datetime import datetime
from pathlib import Path
from typing import Any, Optional


def load_latest_postmortem(postmortem_dir: str = "sentinel/judge/postmortems") -> Optional[dict[str, Any]]:
    """Load the most recent post-mortem JSON file from the postmortem directory."""
    postmortem_path = Path(postmortem_dir)
    if not postmortem_path.exists():
        return None
    
    postmortem_files = sorted(postmortem_path.glob("postmortem_*.json"), reverse=True)
    if not postmortem_files:
        return None
    
    latest = postmortem_files[0]
    with open(latest, "r") as f:
        return json.load(f)


def format_accuracy_section(pm: dict[str, Any]) -> str:
    """Format accuracy metrics as a console string."""
    lines = []
    lines.append("┌─ ACCURACY METRICS ─────────────────────────────────────┐")
    
    accuracy = pm.get("overall_accuracy", {})
    if accuracy:
        correct = accuracy.get("correct_predictions", 0)
        total = accuracy.get("total_predictions", 0)
        pct = (correct / total * 100) if total > 0 else 0
        lines.append(f"│ Correct: {correct}/{total} ({pct:.1f}%)")
        
        up_acc = accuracy.get("up_accuracy", 0)
        down_acc = accuracy.get("down_accuracy", 0)
        lines.append(f"│ Up-move accuracy: {up_acc:.1f}% | Down-move: {down_acc:.1f}%")
    
    lines.append("└────────────────────────────────────────────────────────┘")
    return "\n".join(lines)


def format_confidence_section(pm: dict[str, Any]) -> str:
    """Format confidence calibration metrics as a console string."""
    lines = []
    lines.append("┌─ CONFIDENCE CALIBRATION ──────────────────────────────┐")
    
    calibration = pm.get("confidence_calibration", {})
    if calibration:
        high_conf = calibration.get("high_confidence_accuracy", 0)
        med_conf = calibration.get("medium_confidence_accuracy", 0)
        low_conf = calibration.get("low_confidence_accuracy", 0)
        lines.append(f"│ High confidence (>0.7): {high_conf:.1f}%")
        lines.append(f"│ Medium confidence (0.4-0.7): {med_conf:.1f}%")
        lines.append(f"│ Low confidence (<0.4): {low_conf:.1f}%")
        
        over_under = calibration.get("over_under_confidence", "neutral")
        lines.append(f"│ Calibration bias: {over_under}")
    
    lines.append("└────────────────────────────────────────────────────────┘")
    return "\n".join(lines)


def format_top_predictions_section(pm: dict[str, Any], limit: int = 5) -> str:
    """Format top predictions ranked by confidence."""
    lines = []
    lines.append(f"┌─ TOP {limit} PREDICTIONS ────────────────────────────────────┐")
    
    predictions = pm.get("predictions", [])
    for i, pred in enumerate(predictions[:limit], 1):
        ticker = pred.get("ticker", "???")
        direction = pred.get("predicted_direction", "?").upper()
        confidence = pred.get("confidence_score", 0)
        actual = pred.get("actual_direction", "?").upper()
        correct = "✓" if pred.get("correct", False) else "✗"
        
        lines.append(f"│ {i}. {ticker:6s} {direction:4s} (conf: {confidence:.2f}) → {actual} {correct}")
    
    lines.append("└────────────────────────────────────────────────────────┘")
    return "\n".join(lines)


def format_anomalies_section(pm: dict[str, Any]) -> str:
    """Format anomalies and flagged predictions."""
    lines = []
    anomalies = pm.get("anomalies", [])
    
    if not anomalies:
        lines.append("┌─ ANOMALIES ────────────────────────────────────────────┐")
        lines.append("│ No anomalies detected.")
        lines.append("└────────────────────────────────────────────────────────┘")
        return "\n".join(lines)
    
    lines.append("┌─ ANOMALIES ────────────────────────────────────────────┐")
    for anom in anomalies[:3]:
        ticker = anom.get("ticker", "???")
        anom_type = anom.get("type", "unknown")
        severity = anom.get("severity", "low")
        description = anom.get("description", "")
        
        lines.append(f"│ [{severity.upper()}] {ticker} - {anom_type}")
        if description:
            lines.append(f"│   {description}")
    
    lines.append("└────────────────────────────────────────────────────────┘")
    return "\n".join(lines)


def format_heuristic_refinements_section(pm: dict[str, Any]) -> str:
    """Format heuristic refinements suggested by the Judge."""
    lines = []
    refinements = pm.get("heuristic_refinements", [])
    
    if not refinements:
        lines.append("┌─ REFINEMENTS ──────────────────────────────────────────┐")
        lines.append("│ No refinements suggested.")
        lines.append("└────────────────────────────────────────────────────────┘")
        return "\n".join(lines)
    
    lines.append("┌─ REFINEMENTS ──────────────────────────────────────────┐")
    for ref in refinements[:3]:
        heuristic = ref.get("heuristic", "unknown")
        action = ref.get("action", "")
        rationale = ref.get("rationale", "")
        
        lines.append(f"│ {heuristic}")
        lines.append(f"│   Action: {action}")
        if rationale:
            lines.append(f"│   Rationale: {rationale}")
    
    lines.append("└────────────────────────────────────────────────────────┘")
    return "\n".join(lines)


def print_daily_summary(postmortem_dir: str = "sentinel/judge/postmortems") -> None:
    """Load and print a formatted daily summary of Sentinel performance."""
    pm = load_latest_postmortem(postmortem_dir)
    
    if not pm:
        print("⚠ No post-mortem found. Run the daily pipeline first.")
        return
    
    run_date = pm.get("run_date", "unknown")
    num_tickers = len(pm.get("predictions", []))
    
    print("\n" + "=" * 60)
    print(f"SENTINEL DAILY SUMMARY — {run_date}")
    print(f"Analyzed {num_tickers} ticker(s)")
    print("=" * 60 + "\n")
    
    print(format_accuracy_section(pm))
    print()
    print(format_confidence_section(pm))
    print()
    print(format_top_predictions_section(pm, limit=5))
    print()
