"""
Sentinel Historian — Vector Store Setup and Client Wrapper

This module is the foundation of the Historian agent's RAG pipeline. It
initializes a persistent ChromaDB instance on disk, defines the canonical
collections used across Sentinel (market_events and sec_filings), and
exposes a typed VectorStoreClient wrapper that the rest of the Historian
agent (and the Linguist/Judge agents) use to read and write embeddings.

Collection layout:
  - market_events : historical price-move events with metadata (ticker,
                    date, magnitude, trigger_type). Used by the RAG query
                    interface to surface analogous past events when a new
                    sentiment signal arrives.
  - sec_filings   : chunked text from 8-K / 10-Q filings with metadata
                    (ticker, form_type, filed_date, chunk_index). Used by
                    the Regulatory Whispers detector and Linguistic Drift
                    detector to ground their analyses in primary sources.

Embeddings are generated by ChromaDB's default embedding function
(all-MiniLM-L6-v2 via sentence-transformers) so no external embedding
API call is needed — keeping latency low for high-volume ingestion.

Typical usage:
    from sentinel.historian.vector_store import VectorStoreClient
    client = VectorStoreClient()
    client.upsert_market_event(event_id="AAPL_20240115", ...)
    results = client.query_market_events(query_text="earnings beat guidance", n=5)
"""

from __future__ import annotations

import logging
import os
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Optional

import chromadb
from chromadb.config import Settings

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

COLLECTION_MARKET_EVENTS: str = "market_events"
COLLECTION_SEC_FILINGS: str = "sec_filings"

DEFAULT_DB_PATH: str = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "..",
    "..",
    "data",
    "chromadb",
)

# How many results to return when no explicit n_results is provided.
DEFAULT_N_RESULTS: int = 5


# ---------------------------------------------------------------------------
# Typed result containers
# ---------------------------------------------------------------------------


@dataclass
class MarketEventDocument:
    """A single market-event record returned from a vector similarity query."""

    event_id: str
    ticker: str
    event_date: str          # ISO-8601 date string "YYYY-MM-DD"
    trigger_type: str        # e.g. "earnings_beat", "guidance_cut", "macro_shock"
    price_change_pct: float  # e.g. +7.3 or -12.1
    description: str         # free-text narrative stored as the document body
    distance: float          # cosine distance from query vector (lower = closer)
    extra_metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class SecFilingChunk:
    """A single chunked SEC filing passage returned from a vector similarity query."""

    chunk_id: str
    ticker: str
    form_type: str    # "8-K" or "10-Q"
    filed_date: str   # ISO-8601 date string "YYYY-MM-DD"
    chunk_index: int  # position of this chunk within the full filing
    text: str         # the raw chunk text used as the ChromaDB document
    distance: float   # cosine distance from query vector
    extra_metadata: dict[str, Any] = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Low-level initialiser helpers
# ---------------------------------------------------------------------------


def build_chroma_client(db_path: Optional[str] = None) -> chromadb.ClientAPI:
    """Create (or reopen) a persistent ChromaDB client at *db_path*."""
    resolved_path = db_path or DEFAULT_DB_PATH
    os.makedirs(resolved_path, exist_ok=True)
    logger.info("Initialising ChromaDB persistent client at: %s", resolved_path)
    client = chromadb.PersistentClient(
        path=resolved_path,
        settings=Settings(
            anonymized_telemetry=False,
            allow_reset=True,
        ),
    )
    return client


def ensure_collection(
    client: chromadb.ClientAPI,
    name: str,
    metadata: Optional[dict[str, Any]] = None,
) -> chromadb.Collection:
    """Return a ChromaDB collection, creating it with *metadata* if absent."""
    collection = client.get_or_create_collection(
        name=name,
        metadata=metadata or {},
    )
    logger.debug("Collection ready: '%s' (count=%d)", name, collection.count())
    return collection


# ---------------------------------------------------------------------------
# High-level typed client wrapper
# ---------------------------------------------------------------------------


class VectorStoreClient:
    """
    Thread-safe wrapper around ChromaDB that enforces Sentinel's collection
    schema and returns typed dataclass results instead of raw dicts.

    Parameters
    ----------
    db_path:
        Override the default on-disk path for the ChromaDB directory.
        Useful for tests that want a temporary directory.
    """

    def __init__(self, db_path: Optional[str] = None) -> None:
        """Initialise the ChromaDB client and ensure both collections exist."""
        self._client = build_chroma_client(db_path)
        self._market_events = ensure_collection(
            self._client,
            COLLECTION_MARKET_EVENTS,
            metadata={
                "description": "Historical market price-move events keyed by ticker+date",
                "hnsw:space": "cosine",
            },
        )
        self._sec_filings = ensure_collection(
            self._client,
            COLLECTION_SEC_FILINGS,
            metadata={
                "description": "Chunked SEC 8-K and 10-Q filing text keyed by chunk_id",
                "hnsw:space": "cosine",
            },
        )

    # ------------------------------------------------------------------
    # Market Events — write
    # ------------------------------------------------------------------

    def upsert_market_event(
        self,
        event_id: str,
        ticker: str,
        event_date: str,
        trigger_type: str,
        price_change_pct: float,
        description: str,
        extra_metadata: Optional[dict[str, Any]] = None,
    ) -> None:
        """Insert or overwrite one market-event document in the vector store."""
        metadata: dict[str, Any] = {
            "ticker": ticker,
            "event_date": event_date,
            "trigger_type": trigger_type,
            "price_change_pct": price_change_pct,
            "ingested_at": datetime.utcnow().isoformat(),
        }
        if extra_metadata:
            metadata.update(extra_metadata)

        self._market_events.upsert(
            ids=[event_id],
            documents=[description],
            metadatas=[metadata],
        )
        logger.debug("Upserted market_event id=%s ticker=%s", event_id, ticker)

    def upsert_market_events_batch(
        self,
        records: list[dict[str, Any]],
    ) -> int:
        """
        Bulk-upsert a list of market-event dicts; each dict must contain the
        same keys as the keyword arguments of *upsert_market_event*.
        Returns the number of records written.
        """
        ids, documents, metadatas = [], [], []
        for rec in records:
            ids.append(rec["event_id"])
            documents.append(rec["description"])
            meta: dict[str, Any] = {
                "ticker": rec["ticker"],
                "event_date": rec["event_date"],
                "trigger_type": rec["trigger_type"],
                "price_change_pct": float(rec["price_change_pct"]),
                "ingested_at": datetime.utcnow().isoformat(),
            }
            meta.update(rec.get("extra_metadata") or {})
            metad
